services:
  - type: worker
    name: black-russia-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 8172843951:AAFHMnhFITsIlnA9EwgpVenTHg47UO64bys
